import type ExcelJS from "exceljs";
import { readWorkbookFromFile, pickFirstUsefulWorksheet } from "./excelReader";
import { normalizeExcelDateValue, extractCanonicalDatesFromText, canonicalToDisplayDate, toCanonicalDateOnly } from "../utils/dateUtils";
import { normalizeText } from "../utils/normalizeText";
import { splitAssignees } from "../utils/assignees";
import type { ExcelCellValue, ExcelColumnDefinition, ExcelRow, ParsedPlannerSheet, PlannerCell, PlannerTaskRow } from "../types/excel";
export async function readPlannerExcel(file: File): Promise<ParsedPlannerSheet> { const wb=await readWorkbookFromFile(file); return parseWorksheetAsPlanner(pickFirstUsefulWorksheet(wb)); }
const aliases={name:["nombre","tarea","task"],assignee:["asignado","responsable","owner","assigned"],start:["inicio","start"],end:["fin","finalizacion","due","vencimiento","end"],duration:["duracion","duration"],observations:["observaciones","notes","comentarios"],project:["proyecto","plan"]} as const; type Role=keyof typeof aliases;
function parseWorksheetAsPlanner(ws: ExcelJS.Worksheet): ParsedPlannerSheet { const det=detect(ws); if(!det) throw new Error("No se ha podido detectar la fila de cabecera en el Excel del Planner."); const columns=det.headers.slice(1).map((h,i)=>({index:i,key:normalizeText(h)||`col_${i}`,header:h,visible:!!h.trim()})); const tasks:PlannerTaskRow[]=[]; ws.eachRow({includeEmpty:false},(row,n)=>{ if(n<=det.rowNumber) return; const t=build(row,n,det,columns); if(t) tasks.push(t); }); return {sheetName:ws.name,columns,visibleColumns:columns.filter(c=>c.visible),headerRowNumber:det.rowNumber,tasks}; }
function detect(ws:ExcelJS.Worksheet){ let best:any=null,hitsBest=0; for(let r=1;r<=Math.min(ws.rowCount,30);r++){ const row=ws.getRow(r); const headers:string[]=[]; const roles=new Map<number,Role>(); let hits=0; for(let c=1;c<=row.cellCount;c++){ const txt=cellText(row.getCell(c).value); headers[c]=txt; const role=match(txt); if(role&&!Array.from(roles.values()).includes(role)){roles.set(c,role); hits++;}} if(hits>=2&&hits>hitsBest){best={rowNumber:r,headers,roles};hitsBest=hits;}} return best; }
function match(s:string):Role|null{ const n=normalizeText(s); for(const r of Object.keys(aliases) as Role[]) for(const a of aliases[r]) if(n===normalizeText(a)||n.includes(normalizeText(a))) return r; return null; }
function build(row:ExcelJS.Row,rowNumber:number,det:any,columns:ExcelColumnDefinition[]):PlannerTaskRow|null{ const cells:PlannerCell[]=[]; const rawCells:any[]=[]; let any=false; for(let i=0;i<columns.length;i++){ const cell=row.getCell(i+1); const val=cell.value as ExcelCellValue; const display=cellText(val); if(display.trim()) any=true; const d=normalizeExcelDateValue(val,display); const dates=[...(d?[d]:[]),...extractCanonicalDatesFromText(display)].filter((v,i,a)=>a.indexOf(v)===i); cells.push({header:columns[i].header,address:cell.address,rawValue:val,displayValue:display,canonicalDates:dates.length?dates:undefined}); rawCells.push({value:val,rawText:display,canonicalDate:d??undefined}); } if(!any) return null; const get=(role:Role)=>{ for(const [c,r] of det.roles.entries()) if(r===role){const ce=cells[c-1]; return {text:ce?.displayValue??"", raw:ce?.rawValue??null};} return {text:"",raw:null};}; const name=get("name").text.trim(); const ass=get("assignee").text; const start=normalizeExcelDateValue(get("start").raw,get("start").text); const end=normalizeExcelDateValue(get("end").raw,get("end").text); if(!name&&!start&&!end&&!ass.trim()) return null; const raw:ExcelRow={rowIndex:rowNumber,cells:rawCells}; return {rowIndex:rowNumber,outlineNumber:null,outlineLevel:0,taskNumber:null,name,startCanonical:start,endCanonical:end,durationText:get("duration").text||null,percentComplete:null,assigneesRaw:ass,assignees:splitAssignees(ass),isMilestone:false,dependsOn:null,notes:get("observations").text||null,raw,excelRowNumber:rowNumber,taskName:name,assignee:ass.trim(),startDate:start,endDate:end,duration:get("duration").text,observations:get("observations").text,cells}; }
function cellText(value:unknown):string{ if(value==null) return ""; if(value instanceof Date){const c=toCanonicalDateOnly(value); return c?canonicalToDisplayDate(c):"";} if(typeof value==="object"){const v:any=value; if(Array.isArray(v.richText)) return v.richText.map((p:any)=>p.text??"").join(""); if(typeof v.text==="string") return v.text; if("result" in v) return cellText(v.result);} return String(value); }
