import ExcelJS from "exceljs";
import { readWorkbookFromFile, readWorkbookFromArrayBuffer } from "./excelReader";
import { normalizeText } from "../utils/normalizeText";
import { canonicalDateToExcelSerial, normalizeExcelDateValue, toCanonicalDateOnly, canonicalToDisplayDate } from "../utils/dateUtils";
import type { PlannerTaskRow } from "../types/excel";
import type { LoadedMasterWorkbook, MasterChangeCandidate, MasterInternalRowRef, MasterComparisonRowRef, MasterFieldChange } from "../types/master";
const XLSX_MIME="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
export async function loadMasterWorkbookFromFile(file:File):Promise<LoadedMasterWorkbook>{return loadMasterWorkbook(await readWorkbookFromFile(file));}
export async function loadMasterWorkbookFromArrayBuffer(buffer:ArrayBuffer):Promise<LoadedMasterWorkbook>{return loadMasterWorkbook(await readWorkbookFromArrayBuffer(buffer));}
function loadMasterWorkbook(workbook:ExcelJS.Workbook):LoadedMasterWorkbook{ const internal=workbook.worksheets.find(w=>normalizeText(w.name).includes("seguimiento proyectos"))??workbook.worksheets[0]; if(!internal) throw new Error("El Excel Maestro no contiene hojas."); const comparison=workbook.worksheets.find(w=>w!==internal)??internal; return {comparisonSheetName:comparison.name,internalSheetName:internal.name,comparisonRows:readRows(comparison),internalRows:readRows(internal),_workbook:workbook}; }
function readRows(ws:ExcelJS.Worksheet):MasterInternalRowRef[]&MasterComparisonRowRef[]{ const header=detectHeader(ws); const rows:any[]=[]; ws.eachRow({includeEmpty:false},(row,n)=>{ if(n<=header.row) return; const task=cell(row.getCell(header.name).value); const ass=cell(row.getCell(header.assignee).value); const proj=cell(row.getCell(header.project).value)||null; const s=normalizeExcelDateValue(row.getCell(header.start).value,cell(row.getCell(header.start).value)); const e=normalizeExcelDateValue(row.getCell(header.end).value,cell(row.getCell(header.end).value)); if(task||ass||proj||s||e) rows.push({rowNumber:n,taskName:task,assignee:ass,project:proj,startCanonical:s,endCanonical:e,startColumn:header.start,endColumn:header.end}); }); return rows as any; }
function detectHeader(ws:ExcelJS.Worksheet){ let best={row:1,name:1,assignee:2,project:2,start:3,end:4}; let bestHits=-1; for(let r=1;r<=Math.min(ws.rowCount,40);r++){ const row=ws.getRow(r); let hits=0,res={row:r,name:1,assignee:2,project:2,start:3,end:4}; for(let c=1;c<=Math.min(row.cellCount,120);c++){ const n=normalizeText(cell(row.getCell(c).value)); if(n.includes("detalle")||n.includes("nombre")||n.includes("tarea")){res.name=c;hits++;} if(n.includes("area")||n.includes("persona")||n.includes("responsable")||n.includes("asign")){res.assignee=c;hits++;} if(n.includes("producto")||n.includes("proyecto")||n.includes("plan")){res.project=c;hits++;} if(n.includes("planificada")||n.includes("inicio")){res.start=c;hits++;} if(n.includes("real publicacion")||n.includes("fin")){res.end=c;hits++;} } if(hits>bestHits){best=res;bestHits=hits;} } return best; }
export function validateMasterProject(master:LoadedMasterWorkbook|null, plannerProjectName:string|null){ if(!master) return {valid:false,reason:"Maestro no cargado."}; if(!plannerProjectName) return {valid:false,reason:"No se ha indicado el proyecto del Planner."}; const t=normalizeText(plannerProjectName); const ok=[...master.internalRows,...master.comparisonRows].some(r=>normalizeText(r.project).includes(t)||t.includes(normalizeText(r.project))); return ok?{valid:true}:{valid:false,reason:`El proyecto "${plannerProjectName}" no aparece en el Maestro.`}; }
export function buildMasterChangeCandidates(master:LoadedMasterWorkbook|null, plannerRows:PlannerTaskRow[], plannerProjectName:string|null):MasterChangeCandidate[]{ if(!master) return []; const valid=validateMasterProject(master,plannerProjectName); return plannerRows.map(t=>{ if(!valid.valid) return cand(t,"project_blocked",master,valid.reason); const matches=master.internalRows.filter(r=>normalizeText(r.taskName)===normalizeText(t.taskName)); if(matches.length===0) return cand(t,"not_found",master,"No se encontró una fila equivalente en la hoja interna."); if(matches.length>1) return cand(t,"ambiguous",master,"Coincidencia ambigua."); const m=matches[0]; const changes:MasterFieldChange[]=[]; if((t.startDate??null)!==(m.startCanonical??null)) changes.push({field:"startDate",previous:m.startCanonical,current:t.startDate}); if((t.endDate??null)!==(m.endCanonical??null)) changes.push({field:"endDate",previous:m.endCanonical,current:t.endDate}); return {id:`planner-${t.excelRowNumber}`,status:changes.length?"ready":"no_change",plannerRowIndex:t.excelRowNumber,plannerTaskName:t.taskName,plannerAssignee:t.assignee,plannerProjectName:plannerProjectName??null,internalSheetName:master.internalSheetName,internalRowNumber:m.rowNumber,internalTaskName:m.taskName,internalAssignee:m.assignee,internalProject:m.project,changes}; }); }
function cand(t:PlannerTaskRow,status:any,master:LoadedMasterWorkbook,reason?:string):MasterChangeCandidate{return {id:`planner-${t.excelRowNumber}`,status,reason,plannerRowIndex:t.excelRowNumber,plannerTaskName:t.taskName,plannerAssignee:t.assignee,plannerProjectName:null,internalSheetName:master.internalSheetName,internalRowNumber:null,internalTaskName:null,internalAssignee:null,internalProject:null,changes:[]};}
export async function applyMasterChanges(master:LoadedMasterWorkbook|null, selected:MasterChangeCandidate[]):Promise<Blob>{ if(!master) throw new Error("No hay Maestro cargado."); if(selected.some(c=>c.status==="project_blocked")) throw new Error("El proyecto no está validado en el Maestro. No se puede exportar."); const wb=master._workbook as ExcelJS.Workbook; const sheet=wb.getWorksheet(master.internalSheetName); if(!sheet) throw new Error("No se encuentra la hoja interna."); for(const c of selected.filter(x=>x.status==="ready")){ const ref=master.internalRows.find(r=>r.rowNumber===c.internalRowNumber); if(!ref) continue; for(const ch of c.changes){ const col=ch.field==="startDate"?ref.startColumn:ref.endColumn; if(!col||!ch.current) continue; const serial=canonicalDateToExcelSerial(ch.current); if(serial===null) continue; const cell=sheet.getRow(ref.rowNumber).getCell(col); cell.value=serial; cell.numFmt=typeof cell.numFmt==="string"&&cell.numFmt?cell.numFmt:"dd/mm/yyyy"; }} const buf=await wb.xlsx.writeBuffer(); return new Blob([buf as unknown as ArrayBuffer],{type:XLSX_MIME}); }
function cell(v:unknown):string{ if(v==null)return""; if(v instanceof Date){const c=toCanonicalDateOnly(v); return c?canonicalToDisplayDate(c):"";} if(typeof v==="object"){const o:any=v; if(Array.isArray(o.richText))return o.richText.map((p:any)=>p.text??"").join(""); if(typeof o.text==="string")return o.text; if("result" in o)return cell(o.result);} return String(v).trim(); }
