export function pad2(n: number): string { return n < 10 ? "0" + n : String(n); }
const EXCEL_EPOCH_MS = Date.UTC(1899, 11, 30);
export function excelSerialToCanonicalDate(serial: number): string | null { if (typeof serial !== "number" || !isFinite(serial)) return null; const ms = EXCEL_EPOCH_MS + Math.floor(serial) * 86400000; const d = new Date(ms); return `${d.getUTCFullYear()}-${pad2(d.getUTCMonth()+1)}-${pad2(d.getUTCDate())}`; }
export function canonicalDateToExcelSerial(canonical: string): number | null { const p=parseCanonicalParts(canonical); if(!p) return null; return Math.round((Date.UTC(p.year,p.month-1,p.day)-EXCEL_EPOCH_MS)/86400000); }
export function canonicalToDisplayDate(canonical: string | null | undefined): string { const p=parseCanonicalParts(canonical); return p ? `${pad2(p.day)}/${pad2(p.month)}/${p.year}` : ""; }
export const formatDateForSpain = canonicalToDisplayDate;
export function toCanonicalDateOnly(value: unknown): string | null { if(value===null||value===undefined||value==="") return null; if(value instanceof Date){ if(isNaN(value.getTime())) return null; return `${value.getFullYear()}-${pad2(value.getMonth()+1)}-${pad2(value.getDate())}`;} if(typeof value==="number") return excelSerialToCanonicalDate(value); if(typeof value==="string"){ const s=value.trim(); let m=s.match(/^(\d{4})-(\d{2})-(\d{2})$/); if(m&&validParts(+m[1],+m[2],+m[3])) return `${m[1]}-${m[2]}-${m[3]}`; m=s.match(/^(\d{1,2})[\/\-.](\d{1,2})[\/\-.](\d{2,4})/); if(m){let y=+m[3]; if(y<100)y+=2000; if(validParts(y,+m[2],+m[1])) return `${y}-${pad2(+m[2])}-${pad2(+m[1])}`;} if(/^\d+(\.\d+)?$/.test(s)) return excelSerialToCanonicalDate(Number(s)); } return null; }
export function normalizeExcelDateValue(value: unknown, fallbackText?: string): string | null { return toCanonicalDateOnly(value) ?? (fallbackText ? (toCanonicalDateOnly(fallbackText) ?? extractCanonicalDatesFromText(fallbackText)[0] ?? null) : null); }
export function extractCanonicalDatesFromText(text: unknown): string[] { const s=String(text??""); const out:string[]=[]; const re=/(\d{1,2})[\/\-.](\d{1,2})[\/\-.](\d{2,4})|(\d{4})-(\d{2})-(\d{2})/g; let m; while((m=re.exec(s))){let c:null|string=null; if(m[4]){ if(validParts(+m[4],+m[5],+m[6])) c=`${m[4]}-${m[5]}-${m[6]}`;} else {let y=+m[3]; if(y<100)y+=2000; if(validParts(y,+m[2],+m[1])) c=`${y}-${pad2(+m[2])}-${pad2(+m[1])}`;} if(c&&!out.includes(c)) out.push(c);} return out; }
interface DateParts{year:number;month:number;day:number} function parseCanonicalParts(c:string|null|undefined):DateParts|null{ if(!c)return null; const m=c.match(/^(\d{4})-(\d{2})-(\d{2})$/); if(!m)return null; const p={year:+m[1],month:+m[2],day:+m[3]}; return validParts(p.year,p.month,p.day)?p:null;} function validParts(y:number,m:number,d:number){return isFinite(y)&&isFinite(m)&&isFinite(d)&&y>=1900&&y<=2999&&m>=1&&m<=12&&d>=1&&d<=31;}
